baseBranch: main
workspaceType: pip
packagePatterns:
  - sdk/*/*
  - sdk/

changeKinds:
  breaking:
    versionType: major
    title: Breaking Changes
    description: Changes that break existing features

  feature:
    versionType: minor
    title: Features Added
    description: Adds new features

  bugFix:
    versionType: patch
    title: Bug Fixes
    description: Fixes to existing features

  other:
    versionType: patch
    title: Other Changes
    description: Other Changes
