[packaging]
package_name = "azure-mgmt-crud"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "CRUD Management"
package_doc_id = ""
is_stable = true
is_arm = true
title = "MicrosoftCrudClient"
